config/routes.rb
RailsApiDoc::Engine.routes.draw do
  
  resources :projects do 
  	resources :apis
  	get 'generate_doc' => 'apis#generate_doc', :as => :generate_doc
  end


  resources :parameters


	root to: "projects#index"

end

app/models/rails_api_doc/api.rb
module RailsApiDoc
  class Api < ActiveRecord::Base
    attr_accessible :api_group, :name, :request_type, :url, :version, :parameters_attributes,
     								:success_responses_attributes, :failure_responses_attributes, :project_id
    has_many :parameters, :class_name => "RailsApiDoc::Parameter", dependent: :destroy
    has_many :success_responses, :class_name => "RailsApiDoc::SuccessResponse", dependent: :destroy
    has_many :failure_responses, :class_name => "RailsApiDoc::FailureResponse", dependent: :destroy
    belongs_to :project
    accepts_nested_attributes_for :parameters, :allow_destroy => true, :reject_if => :all_blank
    accepts_nested_attributes_for :success_responses, :allow_destroy => true, :reject_if => :all_blank
    accepts_nested_attributes_for :failure_responses, :allow_destroy => true, :reject_if => :all_blank
    DEFAULT_PAGE_SIZE = 10
  end
end

app/models/rails_api_doc/failure_response.rb
module RailsApiDoc
  class FailureResponse < ActiveRecord::Base
    attr_accessible :api_id, :failure_structure, :note
    belongs_to :api
    validates_presence_of :failure_structure
    validates_presence_of :note
  end
end

app/models/rails_api_doc/parameter.rb
module RailsApiDoc
  class Parameter < ActiveRecord::Base
    attr_accessible :api_id, :name, :note, :param_type
    belongs_to :api
    validates_presence_of :name, :param_type
  end
end

app/models/rails_api_doc/project.rb
module RailsApiDoc
  class Project < ActiveRecord::Base
    attr_accessible :description, :name
    has_many :apis, :dependent => :destroy
    validates_presence_of :name
  end
end

app/models/rails_api_doc/success_response.rb
module RailsApiDoc
  class SuccessResponse < ActiveRecord::Base
    attr_accessible :api_id, :success_structure, :note
    belongs_to :api
    validates_presence_of :success_structure
    validates_presence_of :note
  end
end

app/controllers/rails_api_doc/apis_controller.rb
require_dependency "rails_api_doc/application_controller"

module RailsApiDoc
  class ApisController < ApplicationController
    # GET /apis
    # GET /apis.json
    def index
      @project = Project.find params[:project_id]
      @apis = @project.apis.page(params[:page]).per(RailsApiDoc::Api::DEFAULT_PAGE_SIZE)
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @apis }
      end
    end
  
    # GET /apis/1
    # GET /apis/1.json
    def show
      @project = Project.find params[:project_id]
      @api = Api.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @api }
      end
    end
  
    # GET /apis/new
    # GET /apis/new.json
    def new
      @project = Project.find params[:project_id]
      @api = @project.apis.new
      @parameters = @api.parameters.build
      @api.success_responses.build
      @api.failure_responses.build
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @api }
      end
    end
  
    # GET /apis/1/edit
    def edit
      @project = Project.find params[:project_id]
      @api = Api.find(params[:id])
    end
  
    # POST /apis
    # POST /apis.json
    def create
      @project = Project.find params[:project_id]
      @api = @project.apis.new(params[:api])
      # paramerer_attr = params[:api][:parameters_attributes].delete_if { |k, v| v["name"].blank? }
      respond_to do |format|
        if @api.save
          # paramerer_attr.each do |k, v|
          #   debugger
          #   @api.parameters.create(v)
          # end
          format.html { redirect_to project_apis_path, notice: 'Api was successfully created.' }
          format.json { render json: @api, status: :created, location: @api }
        else
          format.html { render action: "new" }
          format.json { render json: @api.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /apis/1
    # PUT /apis/1.json
    def update
      @project = Project.find params[:project_id]
      @api = @project.apis.find(params[:id])
      # @api.parameters.build
      respond_to do |format|
        if @api.update_attributes(params[:api])
          format.html { redirect_to project_api_path(@project, @api), notice: 'Api was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @api.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /apis/1
    # DELETE /apis/1.json
    def destroy
      @project = Project.find params[:project_id]
      @api = @project.apis.find(params[:id])
      @api.destroy
  
      respond_to do |format|
        format.html { redirect_to project_apis_path }
        format.json { head :no_content }
      end
    end

    def generate_doc
      @project = Project.find params[:project_id]
      puts "dir>>>>>>>>>>>>>>>#{Dir.pwd}"
      project_name = @project.name.gsub(" ", "_")
      _dir = "app/assets/projects/#{project_name}/"
      unless File.directory?(_dir)
        FileUtils.mkdir_p(_dir)
      end
      Dir.chdir(_dir) do 
      puts "dir>>>>>>>>>>>>>>>#{Dir.pwd}"
      apis = @project.apis
      data = ""
      params = ""
      unless apis.blank?
        apis.each do |api|
        data += '/**
* @api {' "#{api.request_type}" +  '}' +   " #{api.url}" + " #{api.name}" + "\n" + 
'* @apiName' +  " #{api.name}"  + "\n" +
'* @apiGroup' + " #{api.api_group}" + "\n" + 
'* @apiVersion' + " #{api.version}" + "\n" +   
'*' +  (val = api.parameters.blank? ? "\n" : api.parameters.map{|p| "\n" + '* @apiParam {' + "#{p.param_type}" + '}' +  " #{p.name}" + " #{p.note}" }.join("")) + "\n" +
'* @apiSuccessExample Success-Response:' + (response = api.success_responses.blank? ? "\n" + "*" + "{}" : "\n" +  api.success_responses.map{|p|  "*" + (note = p.note.blank? ? "" : (p.note + "\n")) + "#{res = p.success_structure.gsub("\r\n", "\n*")}"  + "\n"}.join("")) + "\n"  +
'* @apiErrorExample Error-Response:' + (response = api.failure_responses.blank? ? "\n" + "*" + "{}" : "\n" +  api.failure_responses.map{|p|  "*" + (note = p.note.blank? ? "" : (p.note + "\n")) + "#{res = p.failure_structure.gsub("\r\n", "\n*")}"  + "\n"}.join("")) + "\n"  + 
"*/" + "\n" 
end

      File.open("api.js", 'w+') {
        |f| f.write("#{data}") 
      }

      # write package file
      package_data = '{
        "name": '+  '"' + @project.name + ' APIDOC",
        "version": "0.1.0",
        "description": "Documentation for RESTful web APIs"
      }'
      File.open("package.json", 'w+') {
        |f| f.write("#{package_data}") 
      }

      end
      system "apidoc"
    end
      flash[:notice] = "Api Doc Generated"
      redirect_to project_apis_path(@project)
    end
  end

end

app/controllers/rails_api_doc/application_controller.rb
module RailsApiDoc
  class ApplicationController < ActionController::Base
  end
end

app/controllers/rails_api_doc/parameters_controller.rb
require_dependency "rails_api_doc/application_controller"

module RailsApiDoc
  class ParametersController < ApplicationController
    # GET /parameters
    # GET /parameters.json
    def index
      @parameters = Parameter.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @parameters }
      end
    end
  
    # GET /parameters/1
    # GET /parameters/1.json
    def show
      @parameter = Parameter.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @parameter }
      end
    end
  
    # GET /parameters/new
    # GET /parameters/new.json
    def new
      @parameter = Parameter.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @parameter }
      end
    end
  
    # GET /parameters/1/edit
    def edit
      @parameter = Parameter.find(params[:id])
    end
  
    # POST /parameters
    # POST /parameters.json
    def create
      @parameter = Parameter.new(params[:parameter])
  
      respond_to do |format|
        if @parameter.save
          format.html { redirect_to @parameter, notice: 'Parameter was successfully created.' }
          format.json { render json: @parameter, status: :created, location: @parameter }
        else
          format.html { render action: "new" }
          format.json { render json: @parameter.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /parameters/1
    # PUT /parameters/1.json
    def update
      @parameter = Parameter.find(params[:id])
  
      respond_to do |format|
        if @parameter.update_attributes(params[:parameter])
          format.html { redirect_to @parameter, notice: 'Parameter was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @parameter.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /parameters/1
    # DELETE /parameters/1.json
    def destroy
      @parameter = Parameter.find(params[:id])
      @parameter.destroy
  
      respond_to do |format|
        format.html { redirect_to parameters_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/rails_api_doc/projects_controller.rb
require_dependency "rails_api_doc/application_controller"

module RailsApiDoc
  class ProjectsController < ApplicationController
    # GET /projects
    # GET /projects.json
    def index
      @projects = Project.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @projects }
      end
    end
  
    # GET /projects/1
    # GET /projects/1.json
    def show
      @project = Project.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @project }
      end
    end
  
    # GET /projects/new
    # GET /projects/new.json
    def new
      @project = Project.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @project }
      end
    end
  
    # GET /projects/1/edit
    def edit
      @project = Project.find(params[:id])
    end
  
    # POST /projects
    # POST /projects.json
    def create
      @project = Project.new(params[:project])
  
      respond_to do |format|
        if @project.save
          format.html { redirect_to @project, notice: 'Project was successfully created.' }
          format.json { render json: @project, status: :created, location: @project }
        else
          format.html { render action: "new" }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /projects/1
    # PUT /projects/1.json
    def update
      @project = Project.find(params[:id])
  
      respond_to do |format|
        if @project.update_attributes(params[:project])
          format.html { redirect_to @project, notice: 'Project was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /projects/1
    # DELETE /projects/1.json
    def destroy
      @project = Project.find(params[:id])
      @project.destroy
  
      respond_to do |format|
        format.html { redirect_to projects_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/rails_api_doc/apis_helper.rb
module RailsApiDoc
  module ApisHelper

  	def link_to_add_fields(name, f, association)
	    new_object = f.object.class.reflect_on_association(association).klass.new
	    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
	      render(association.to_s.singularize + "_fields", :f => builder)
	    end
	    link_to_function(name, ("add_fields(this, '#{association}', '#{escape_javascript(fields)}')"))
  	end

  	def link_to_add_success_fields(name, f, association)
	    new_object = f.object.class.reflect_on_association(association).klass.new
	    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
	      render(association.to_s.singularize + "_fields", :f => builder)
	    end
	    link_to_function(name, ("add_success_fields(this, '#{association}', '#{escape_javascript(fields)}')"))
  	end

  	def link_to_add_failure_fields(name, f, association)
	    new_object = f.object.class.reflect_on_association(association).klass.new
	    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
	      render(association.to_s.singularize + "_fields", :f => builder)
	    end
	    link_to_function(name, ("add_failure_fields(this, '#{association}', '#{escape_javascript(fields)}')"))
  	end
  	
  end
end

app/helpers/rails_api_doc/application_helper.rb
module RailsApiDoc
  module ApplicationHelper
  end
end

app/helpers/rails_api_doc/parameters_helper.rb
module RailsApiDoc
  module ParametersHelper
  end
end

app/helpers/rails_api_doc/projects_helper.rb
module RailsApiDoc
  module ProjectsHelper
  end
end

app/views/rails_api_doc/apis/_failure_response_fields.html.erb
<div>
	<div class="failure-field">
	  <%= f.label :failure_note %><br />
	  <%= f.text_field :note %>
	</div>
	<div class="failure-field">
	  <%= f.label :failure_response_structure %><br />
	  <%= f.text_area :failure_structure %>
	</div>
</div>

app/views/rails_api_doc/apis/_form.html.erb
<script src="http://code.jquery.com/jquery-latest.min.js"></script>

<%= form_for [@project, @api] do |f| %>
  <% if @api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api.errors.count, "error") %> prohibited this api from being saved:</h2>

      <ul>
      <% @api.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-fields">
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :required => "true" %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url, :required => "true" %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version, :required => "true" %>
  </div>
  <div class="field">
    <%= f.label :request_type %><br />
    <%= f.text_field :request_type, :required => "true" %>
  </div>
  <div class="field">
    <%= f.label :api_group %><br />
    <%= f.text_field :api_group, :required => "true" %>
  </div>
</div>
<div class="clear"></div>
  <h1>Parameters</h1>
  <div class="nested-fields">
    <%= f.fields_for :parameters do |ff| %>
      <%= render "parameter_fields", :f => ff %>
    <% end %>
  </div>
  <div class="link-to-add-more"><%= link_to_add_fields "Add More Parameters", f, :parameters %></div>
<div class="clear"></div>
  <h1>Success Response</h1>
  <div class="success-fields">
    <%= f.fields_for :success_responses do |ff| %>
      <%= render "success_response_fields", :f => ff %>
    <% end %>
  </div>
  <div class="link-to-add-more"><%= link_to_add_success_fields "Add More Success Response", f, :success_responses %></div>
<div class="clear"></div>
  <h1>Failure Response</h1>
  <div class="failure-fields">
    <%= f.fields_for :failure_responses do |ff| %>
      <%= render "failure_response_fields", :f => ff %>
    <% end %>
  </div>
  <div class="link-to-add-more"><%= link_to_add_failure_fields "Add More Failure Response", f, :failure_responses %></div>
  <div class="clear"></div>
  <div class="actions">
    <%= f.submit "Create API", :class => "btn create_api_btn" %>
  </div>

<% end %>

app/views/rails_api_doc/apis/_parameter_fields.html.erb
<div>
	<div class="param-field">
	  <%= f.label :name %><br />
	  <%= f.text_field :name %>
	</div>

	<div class="param-field">
	  <%= f.label :param_type %><br />
	  <%= f.text_field :param_type %>
	</div>

	<div class="param-field">
	  <%= f.label :description %><br />
	  <%= f.text_field :note %>
	</div>
</div>
<br />

app/views/rails_api_doc/apis/_success_response_fields.html.erb
<div>
	<div class="success-field">
	  <%= f.label :success_note %><br />
	  <%= f.text_field :note %>
	</div>
	<div class="success-field">
	  <%= f.label :success_response_structure %><br />
	  <%= f.text_area :success_structure %>
	</div>
</div>

app/views/rails_api_doc/apis/edit.html.erb
<h1>Editing api</h1>

<%= render 'form' %>

<%= link_to 'Show', project_api_path(@project, @api) %> |
<%= link_to 'Back', project_apis_path %>

app/views/rails_api_doc/apis/index.html.erb
<h3><%= flash[:notice] %></h3>
<h1>Listing apis</h1><br />
<% @apis.each do |api| %>
    <h3>API Name : <%= api.name %></h3>
    <pre class="prettyprint language-html prettyprinted" data-type="get" style="">
      <code>
        <span class="pln"><strong>URL: </strong><%= api.url %></span><br />
        <span class="pln"><strong>Version: </strong><%= api.version %></span><br />
        <span class="pln"><strong>Request: </strong><%= api.request_type %></span><br />
        <span class="pln"><strong>API Group: </strong><%= api.api_group %></span><br />
        <span class="pln link"><%= link_to 'View Details', project_api_path(@project, api) %> | <%= link_to 'Edit', edit_project_api_path(@project, api) %> | <%= link_to 'Destroy', project_api_path(@project, api), method: :delete, data: { confirm: 'Are you sure?' } %></span>
      </code>
    </pre>
   
<% end %>
<br />
<%= paginate @apis %>

<%= link_to 'New Api', new_project_api_path %>|
<%= link_to 'Generate Api Doc', project_generate_doc_path %>|
<%= link_to 'All Projects', projects_path%>

app/views/rails_api_doc/apis/new.html.erb
<div class="clear"></div>
<h1 style="margin-left:15px">New api</h1>
<%= render 'form' %>

|<%= link_to 'Back', project_apis_path %>

app/views/rails_api_doc/apis/show.html.erb
<p id="notice"><%= notice %></p>

<br /><h3>This API is Listed under Project - "<%= @api.project.name %>"</h3><br />
<h4>API Name : <%= @api.name %></h4>
    <pre class="prettyprint language-html prettyprinted" data-type="get" style="">
      <code>
        <span class="pln"><strong class="green">URL: </strong><%= @api.url %></span><br />
        <span class="pln"><strong class="green">Version: </strong><%= @api.version %></span><br />
        <span class="pln"><strong class="green">Request: </strong><%= @api.request_type %></span><br />
        <span class="pln"><strong class="green">API Group: </strong><%= @api.api_group %></span><br />
        <span class="pln"><strong class="big-font">Parameters: </strong></span><br />
        <% @api.parameters.each do |p|%>
          <span class="pln"><strong class="green">Name: </strong><%= p.name %></span><br />
          <span class="pln"><strong class="green">Type: </strong><%= p.param_type%></span><br />
          <span class="pln"><strong class="green">Note: </strong><%= p.note%></span><br />
        <% end %>
        <span class="pln"><strong class="big-font">Succes Response: </strong></span><br />
        <% @api.success_responses.each do |p|%>
          <span class="pln"><strong class="green">Note: </strong><%= p.note %></span><br />
          <span class="pln"><strong class="green">Response: </strong></span><%= p.success_structure %><br /><br />
        <% end %>
        <span class="pln"><strong class="big-font">Failure Responses: </strong></span><br />
        <% @api.failure_responses.each do |p|%>
          <span class="pln"><strong class="green">Note: </strong><%= p.note%></span><br />
          <span class="pln"><strong class="green">Type: </strong></span><%= p.failure_structure%><br /><br />
        <% end %>
      </code>
    </pre>

<%= link_to 'Edit', edit_project_api_path(@project, @api) %> |
<%= link_to 'Back', project_apis_path(@project) %>